version: 2

sources:
  - name: devstage
    schema: devstage # Redshift schema name
    tables:
      - name: productlines # Table name in Redshift
      - name: products
      - name: offices
      - name: employees
      - name: customers
      - name: payments
      - name: orders
      - name: orderdetails